export const MenuList=[
    {
        title:'Home',
        url:'/'
    },
    {
        title:'About',
        url:'/About'
    },
    {
        title:'Services',
        url:'/Services'
    },
    {
        title:'Testimonal',
        url:'/Testimonal'
    },
    {
        title:'Contact',
        url:'/Contact'
    }
];